@isTest
public class DemoApexSF2 {
private Integer num;
    
    public static void helloMethod() {
        System.debug('Change Hello DemoApexSF2 new changes');
    }
    
    public static void testNewMethod() {
        System.debug('Change Hello DemoApexSF2 new changes');
    System.debug('Change Hello DemoApexSF2 new changes');
    System.debug('Change Hello DemoApexSF2 new changes 17-10-23');
    }
}