@isTest
public class TemperatureConverterTest {
    //test class
    /*@isTest
    static void testCelsiusToFahrenheit() {
        Decimal celsius = 0;
        Decimal expectedFahrenheit = 32;
        Decimal actualFahrenheit = TemperatureConverter.celsiusToFahrenheit(celsius);
        System.assertEquals(expectedFahrenheit, actualFahrenheit, '0°C should be 32°F');
    }
    @isTest
    static void testFahrenheitToCelsius() {
        Decimal fahrenheit = 32;
        Decimal expectedCelsius = 0;
        Decimal actualCelsius = TemperatureConverter.fahrenheitToCelsius(fahrenheit);
        System.assertEquals(expectedCelsius, actualCelsius, '32°F should be 0°C');
    }*/
}